[package]
name = "faff-core"
build = "build.rs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "faff_core"
crate-type = ["rlib"]

[features]
default = []
python = ["dep:pyo3", "dep:pythonize"]

[dependencies]
# Serialization
serde.workspace = true
serde_json.workspace = true
serde_canonical_json.workspace = true

# Date/time handling
chrono.workspace = true
chrono-tz.workspace = true

# Python integration (for plugin system) - optional
pyo3 = { workspace = true, optional = true }
pythonize = { workspace = true, optional = true }

# Utilities
slug.workspace = true
anyhow.workspace = true
thiserror.workspace = true
toml.workspace = true
regex.workspace = true
glob.workspace = true
base64.workspace = true
rand.workspace = true

# Cryptography (for identities)
ed25519-dalek.workspace = true
sha2.workspace = true
hex.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
vergen-gix = { version = "1.0.0" }