name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  prepare-release:
    name: Prepare release version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          # Remove 'v' prefix from tag
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Release version: $TAG_VERSION"
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in Cargo.toml
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "chore: release version $VERSION"
          git push origin HEAD:main

  build-wheels:
    name: Build wheels on ${{ matrix.platform.os }}
    needs: prepare-release
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read

    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            os: linux
          - runner: macos-13  # x86_64
            os: macos
          - runner: macos-14  # ARM64
            os: macos-arm
          - runner: windows-latest
            os: windows

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # Get the version update commit
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: bindings-python
          command: build
          args: --release --out dist
          manylinux: ${{ matrix.platform.os == 'linux' && 'auto' || '' }}

      - name: Upload wheels to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.os }}
          path: bindings-python/dist

  publish-to-pypi:
    name: Publish release to PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --skip-existing dist/*
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    needs: [prepare-release, publish-to-pypi]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ needs.prepare-release.outputs.version }}
          files: dist/*
          draft: false
          prerelease: false

  bump-for-next-dev:
    name: Bump version for next dev cycle
    needs: [prepare-release, publish-to-pypi]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Bump to next patch version
        run: |
          CURRENT_VERSION="${{ needs.prepare-release.outputs.version }}"
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}"

          echo "Bumping from $CURRENT_VERSION to $NEXT_VERSION for next dev cycle"
          sed -i "s/^version = \".*\"/version = \"$NEXT_VERSION\"/" Cargo.toml

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "chore: bump version to $NEXT_VERSION for next dev cycle [skip ci]"
          git push
